[31m[2024-09-02 15:09:37] ERROR 15:09:13 CST [GreetingsModule] Greetings

[0m[32m[2024-09-02 15:09:37] INFO 

[0m[32m[2024-09-02 15:09:37] INFO 

[0m[32m[2024-09-02 15:09:37] INFO  _   __      _          _   __           

[0m[32m[2024-09-02 15:09:37] INFO | | / /     | |        | | / /           

[0m[32m[2024-09-02 15:09:37] INFO | |/ / _   _| |__   ___| |/ /  ___ _   _ 

[0m[32m[2024-09-02 15:09:37] INFO |    \| | | | '_ \ / _ \    \ / _ \ | | |

[0m[32m[2024-09-02 15:09:37] INFO | |\  \ |_| | |_) |  __/ |\  \  __/ |_| |

[0m[32m[2024-09-02 15:09:37] INFO \_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |

[0m[32m[2024-09-02 15:09:37] INFO                                     __/ |

[0m[32m[2024-09-02 15:09:37] INFO                                    |___/

[0m[32m[2024-09-02 15:09:37] INFO 

[0m[31m[2024-09-02 15:09:37] ERROR 15:09:13 CST message: [registry]

[0m[31m[2024-09-02 15:09:37] ERROR Greetings, KubeKey!

[0m[31m[2024-09-02 15:09:38] ERROR 15:09:13 CST message: [node1]

[0m[31m[2024-09-02 15:09:38] ERROR Greetings, KubeKey!

[0m[31m[2024-09-02 15:09:38] ERROR 15:09:13 CST success: [registry]

[0m[31m[2024-09-02 15:09:38] ERROR 15:09:13 CST success: [node1]

[0m[31m[2024-09-02 15:09:38] ERROR 15:09:13 CST [DeleteClusterConfirmModule] Display confirmation form

[0m[31m[2024-09-02 15:09:38] ERROR 15:09:13 CST success: [LocalHost]

[0m[31m[2024-09-02 15:09:38] ERROR 15:09:13 CST [ResetClusterModule] Reset the cluster using kubeadm

[0m[31m[2024-09-02 15:09:40] ERROR 15:09:16 CST stdout: [node1]

[0m[31m[2024-09-02 15:09:40] ERROR [reset] Reading configuration from the cluster...

[0m[31m[2024-09-02 15:09:40] ERROR [reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'

[0m[31m[2024-09-02 15:09:40] ERROR W0902 15:09:14.011394   24714 utils.go:69] The recommended value for "clusterDNS" in "KubeletConfiguration" is: [10.233.0.10]; the provided value is: [169.254.25.10]

[0m[31m[2024-09-02 15:09:40] ERROR [preflight] Running pre-flight checks

[0m[31m[2024-09-02 15:09:40] ERROR W0902 15:09:14.023055   24714 removeetcdmember.go:84] [reset] No kubeadm config, using etcd pod spec to get data directory

[0m[31m[2024-09-02 15:09:40] ERROR [reset] No etcd config found. Assuming external etcd

[0m[31m[2024-09-02 15:09:40] ERROR [reset] Please, manually reset etcd to prevent further issues

[0m[31m[2024-09-02 15:09:40] ERROR [reset] Stopping the kubelet service

[0m[31m[2024-09-02 15:09:40] ERROR [reset] Unmounting mounted directories in "/var/lib/kubelet"

[0m[31m[2024-09-02 15:09:40] ERROR W0902 15:09:16.084521   24714 cleanupnode.go:93] [reset] Failed to remove containers: [failed to stop running pod 70c6ca758b2abd6a047861f09c7bc8ee9048b413498461c08ad20815a0c66bcf: output: E0902 15:09:15.964615   25583 remote_runtime.go:248] "StopPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to destroy network for sandbox \"70c6ca758b2abd6a047861f09c7bc8ee9048b413498461c08ad20815a0c66bcf\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": dial tcp 10.233.0.1:443: connect: connection refused" podSandboxID="70c6ca758b2abd6a047861f09c7bc8ee9048b413498461c08ad20815a0c66bcf"

[0m[31m[2024-09-02 15:09:40] ERROR time="2024-09-02T15:09:15+08:00" level=fatal msg="stopping the pod sandbox \"70c6ca758b2abd6a047861f09c7bc8ee9048b413498461c08ad20815a0c66bcf\": rpc error: code = Unknown desc = failed to destroy network for sandbox \"70c6ca758b2abd6a047861f09c7bc8ee9048b413498461c08ad20815a0c66bcf\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": dial tcp 10.233.0.1:443: connect: connection refused"

[0m[31m[2024-09-02 15:09:40] ERROR , error: exit status 1, failed to stop running pod a9a529431ba8551f2dfbae7c19fe4c84dde31b1c3e8f1711ba55bfa9ab20b15d: output: E0902 15:09:15.989374   25605 remote_runtime.go:248] "StopPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to destroy network for sandbox \"a9a529431ba8551f2dfbae7c19fe4c84dde31b1c3e8f1711ba55bfa9ab20b15d\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": dial tcp 10.233.0.1:443: connect: connection refused" podSandboxID="a9a529431ba8551f2dfbae7c19fe4c84dde31b1c3e8f1711ba55bfa9ab20b15d"

[0m[31m[2024-09-02 15:09:40] ERROR time="2024-09-02T15:09:15+08:00" level=fatal msg="stopping the pod sandbox \"a9a529431ba8551f2dfbae7c19fe4c84dde31b1c3e8f1711ba55bfa9ab20b15d\": rpc error: code = Unknown desc = failed to destroy network for sandbox \"a9a529431ba8551f2dfbae7c19fe4c84dde31b1c3e8f1711ba55bfa9ab20b15d\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": dial tcp 10.233.0.1:443: connect: connection refused"

[0m[31m[2024-09-02 15:09:40] ERROR , error: exit status 1, failed to stop running pod ccc822607f8baf1ff1baea959715d10d5e083b28950b1d46cefc7da65f0a1f01: output: E0902 15:09:16.011970   25627 remote_runtime.go:248] "StopPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to destroy network for sandbox \"ccc822607f8baf1ff1baea959715d10d5e083b28950b1d46cefc7da65f0a1f01\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": dial tcp 10.233.0.1:443: connect: connection refused" podSandboxID="ccc822607f8baf1ff1baea959715d10d5e083b28950b1d46cefc7da65f0a1f01"

[0m[31m[2024-09-02 15:09:40] ERROR time="2024-09-02T15:09:16+08:00" level=fatal msg="stopping the pod sandbox \"ccc822607f8baf1ff1baea959715d10d5e083b28950b1d46cefc7da65f0a1f01\": rpc error: code = Unknown desc = failed to destroy network for sandbox \"ccc822607f8baf1ff1baea959715d10d5e083b28950b1d46cefc7da65f0a1f01\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: Get \"https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": dial tcp 10.233.0.1:443: connect: connection refused"

[0m[31m[2024-09-02 15:09:40] ERROR , error: exit status 1]

[0m[31m[2024-09-02 15:09:40] ERROR [reset] Deleting contents of directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]

[0m[31m[2024-09-02 15:09:40] ERROR [reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

[0m[31m[2024-09-02 15:09:40] ERROR [reset] Deleting contents of stateful directories: [/var/lib/kubelet /var/lib/dockershim /var/run/kubernetes /var/lib/cni]

[0m[31m[2024-09-02 15:09:40] ERROR 

[0m[31m[2024-09-02 15:09:40] ERROR The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d

[0m[31m[2024-09-02 15:09:40] ERROR 

[0m[31m[2024-09-02 15:09:40] ERROR The reset process does not reset or clean up iptables rules or IPVS tables.

[0m[31m[2024-09-02 15:09:40] ERROR If you wish to reset iptables, you must do so manually by using the "iptables" command.

[0m[31m[2024-09-02 15:09:40] ERROR 

[0m[31m[2024-09-02 15:09:40] ERROR If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)

[0m[31m[2024-09-02 15:09:40] ERROR to reset your system's IPVS tables.

[0m[31m[2024-09-02 15:09:40] ERROR 

[0m[31m[2024-09-02 15:09:40] ERROR The reset process does not clean your kubeconfig files and you must remove them manually.

[0m[31m[2024-09-02 15:09:40] ERROR Please, check the contents of the $HOME/.kube/config file.

[0m[31m[2024-09-02 15:09:40] ERROR 15:09:16 CST success: [node1]

[0m[31m[2024-09-02 15:09:40] ERROR 15:09:16 CST [ClearOSModule] Reset os network config

[0m[31m[2024-09-02 15:09:41] ERROR 15:09:17 CST stdout: [node1]

[0m[31m[2024-09-02 15:09:41] ERROR Cannot find device "kube-ipvs0"

[0m[31m[2024-09-02 15:09:41] ERROR 15:09:17 CST success: [node1]

[0m[31m[2024-09-02 15:09:41] ERROR 15:09:17 CST [ClearOSModule] Uninstall etcd

[0m[31m[2024-09-02 15:09:42] ERROR 15:09:18 CST success: [node1]

[0m[31m[2024-09-02 15:09:42] ERROR 15:09:18 CST [ClearOSModule] Remove cluster files

[0m[31m[2024-09-02 15:09:46] ERROR 15:09:22 CST success: [node1]

[0m[31m[2024-09-02 15:09:46] ERROR 15:09:22 CST [ClearOSModule] Systemd daemon reload

[0m[31m[2024-09-02 15:09:47] ERROR 15:09:23 CST success: [node1]

[0m[31m[2024-09-02 15:09:47] ERROR 15:09:23 CST [UninstallAutoRenewCertsModule] UnInstall auto renew control-plane certs

[0m[31m[2024-09-02 15:09:48] ERROR 15:09:24 CST success: [node1]

[0m[31m[2024-09-02 15:09:48] ERROR 15:09:24 CST Pipeline[DeleteClusterPipeline] execute successfully

[0m[32m[2024-09-02 15:09:48] INFO Pipeline Done

[0m[32m[2024-09-02 15:09:48] INFO 
[0m[32m[2024-09-02 15:09:48] INFO Are you sure to delete this cluster? [yes/no]: 

[0m